version: '3'
services:
  frontend:
    container_name: client
    build:
      context: ./
    ports:
      - "5000:5000"
    
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    
    
